# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostl < Formula
  desc "3D model file combiner and SCAD renderer"
  homepage "https://github.com/philipparndt/gostl"
  version "0.2.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/philipparndt/gostl/releases/download/v0.2.0/gostl_darwin_x86_64.tar.gz"
    sha256 "ec5cf60c42fd27c2f9e4952ba95c2c931362505dc2f70e0a24477effb3f2ba86"

    def install
      bin.install "gostl"
      bash_completion.install "completions/gostl.bash" => "gostl"
      zsh_completion.install "completions/_gostl"
      fish_completion.install "completions/gostl.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/philipparndt/gostl/releases/download/v0.2.0/gostl_darwin_arm64.tar.gz"
    sha256 "24c2b76b7cef63c9a49ba8ad96e318612c4c48d52fe3b923c229f83fd1a1e1ef"

    def install
      bin.install "gostl"
      bash_completion.install "completions/gostl.bash" => "gostl"
      zsh_completion.install "completions/_gostl"
      fish_completion.install "completions/gostl.fish"
    end
  end
end
