# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostl < Formula
  desc "3D model file combiner and SCAD renderer"
  homepage "https://github.com/philipparndt/gostl"
  version "0.1.3"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/philipparndt/gostl/releases/download/v0.1.3/gostl_darwin_x86_64.tar.gz"
    sha256 "bf19a3c444cd6d14f339710ab3e94fe79db35ab4b20458ba0501033d9fff55ab"

    def install
      bin.install "gostl"
      bash_completion.install "completions/gostl.bash" => "gostl"
      zsh_completion.install "completions/_gostl"
      fish_completion.install "completions/gostl.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/philipparndt/gostl/releases/download/v0.1.3/gostl_darwin_arm64.tar.gz"
    sha256 "48f38400bdca2c4492a31174e18061d24d480f666bc598cbfe036bcbc3b39ede"

    def install
      bin.install "gostl"
      bash_completion.install "completions/gostl.bash" => "gostl"
      zsh_completion.install "completions/_gostl"
      fish_completion.install "completions/gostl.fish"
    end
  end
end
