# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostl < Formula
  desc "3D model file combiner and SCAD renderer"
  homepage "https://github.com/philipparndt/gostl"
  version "0.3.0"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/philipparndt/gostl/releases/download/v0.3.0/gostl_darwin_x86_64.tar.gz"
    sha256 "a52fa24a10be1fb2b7e1d5aeee68b5ef694fef06a1cc656a8a5fa281f9f19dee"

    def install
      bin.install "gostl"
      bash_completion.install "completions/gostl.bash" => "gostl"
      zsh_completion.install "completions/_gostl"
      fish_completion.install "completions/gostl.fish"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/philipparndt/gostl/releases/download/v0.3.0/gostl_darwin_arm64.tar.gz"
    sha256 "ac34663176dfc0b702e1e7e901c7b114bad46206e75a1578c45be1cd492d093e"

    def install
      bin.install "gostl"
      bash_completion.install "completions/gostl.bash" => "gostl"
      zsh_completion.install "completions/_gostl"
      fish_completion.install "completions/gostl.fish"
    end
  end
end
